package morse;

public final class MorseTraits {

    public static final String ONE_SPACE = " ";
    public static final String FOUR_SPACES = "    ";
    
    public static final String WORD_SEPARATOR = "";

    public static final String ALNUM_A = "a";
    public static final String ALNUM_B = "b";
    public static final String ALNUM_C = "c";
    public static final String ALNUM_D = "d";
    public static final String ALNUM_E = "e";
    public static final String ALNUM_F = "f";
    public static final String ALNUM_G = "g";
    public static final String ALNUM_H = "h";
    public static final String ALNUM_I = "i";
    public static final String ALNUM_J = "j";
    public static final String ALNUM_K = "k";
    public static final String ALNUM_L = "l";
    public static final String ALNUM_M = "m";
    public static final String ALNUM_N = "n";
    public static final String ALNUM_O = "o";
    public static final String ALNUM_P = "p";
    public static final String ALNUM_Q = "q";
    public static final String ALNUM_R = "r";
    public static final String ALNUM_S = "s";
    public static final String ALNUM_T = "t";
    public static final String ALNUM_U = "u";
    public static final String ALNUM_V = "v";
    public static final String ALNUM_W = "w";
    public static final String ALNUM_X = "x";
    public static final String ALNUM_Y = "y";
    public static final String ALNUM_Z = "z";
    public static final String ALNUM_0 = "0";
    public static final String ALNUM_1 = "1";
    public static final String ALNUM_2 = "2";
    public static final String ALNUM_3 = "3";
    public static final String ALNUM_4 = "4";
    public static final String ALNUM_5 = "5";
    public static final String ALNUM_6 = "6";
    public static final String ALNUM_7 = "7";
    public static final String ALNUM_8 = "8";
    public static final String ALNUM_9 = "9";

    public static final String MORSE_A = ".-";
    public static final String MORSE_B = "-...";
    public static final String MORSE_C = "-.-.";
    public static final String MORSE_D = "-..";
    public static final String MORSE_E = ".";
    public static final String MORSE_F = "..-.";
    public static final String MORSE_G = "--.";
    public static final String MORSE_H = "....";
    public static final String MORSE_I = "..";
    public static final String MORSE_J = ".---";
    public static final String MORSE_K = "-.-";
    public static final String MORSE_L = ".-..";
    public static final String MORSE_M = "--";
    public static final String MORSE_N = "-.";
    public static final String MORSE_O = "---";
    public static final String MORSE_P = ".--.";
    public static final String MORSE_Q = "--.-";
    public static final String MORSE_R = ".-.";
    public static final String MORSE_S = "...";
    public static final String MORSE_T = "-";
    public static final String MORSE_U = "..-";
    public static final String MORSE_V = "...-";
    public static final String MORSE_W = ".--";
    public static final String MORSE_X = "-..-";
    public static final String MORSE_Y = "-.--";
    public static final String MORSE_Z = "--..";
    public static final String MORSE_0 = "-----";
    public static final String MORSE_1 = ".----";
    public static final String MORSE_2 = "..---";
    public static final String MORSE_3 = "...--";
    public static final String MORSE_4 = "....-";
    public static final String MORSE_5 = ".....";
    public static final String MORSE_6 = "-....";
    public static final String MORSE_7 = "--...";
    public static final String MORSE_8 = "---..";
    public static final String MORSE_9 = "----.";
}
